### ISSUE TITLE
Tela de Menu

### ISSUE THREAD

**Issue by MateusO97** [Microcervejaria/Microcervejaria-App#22]
**Descreva a solução que você gostaria**

Adicionar os botões para iniciar processo, iniciar limpeza e criar receita na tela de menu, ajustar o menu de navegação superior.

**Descreva uma alternativa considerada**

Utilizar os botões do menu inferior seguindo os padrões do protótipo

**Informações adicionais**

**Checklist**  
- [ ] A issue possui nome significativo.
- [ ] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [ ] A issue possui labels.

**Comment by cantuariavc** [comment]
f23d7d971d1b7c860812ec6a8cdd4a768c484f17
