### ISSUE TITLE
Criar menu de navegação

### ISSUE THREAD

**Issue by MateusO97** [Microcervejaria/Microcervejaria-App#3]
**Descreva a solução que você gostaria**

Criação da estrutura do componente do menu de navegação.

**Descreva uma alternativa considerada**

O menu deve aparecer em todas as telas após o usuário estar autenticado, e o titulo do menu sera o nome da página na qual o usuário se encontra

**Informações adicionais**

A estrutura do menu pode ser feito de uma forma que seja um componente adicionado em todas as páginas manualmente no lugar de ser feito de forma automática, e nesta adição do componente o nome da página seria uma das propriedades dele

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by cantuariavc** [comment]
e8631be2c0c539966abbe2bd73728a944977fae8
